version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/BE.Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/
    depends_on:
      - db
    restart: always

  db:
    build:
      context: .
      dockerfile: database/DB.Dockerfile
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: