version: "3.9"

services:
  backend:
    image: saurio96/backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/
    depends_on:
      - db
    restart: always

  db:
    image: saurio96/database
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: