version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/FE.Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    restart: always

volumes:
  mongo_data: